/* ==== Test Created with Cypress Studio ==== */
it('gen1', function() {
  /* ==== Generated with Cypress Studio ==== */
  cy.visit('https://cordemo.usecology.com/');
  cy.get('#user').type('manand84');
  cy.get('#passwrd').type('Changeme!@2345');
  cy.get('#login').click();
  cy.wait(40000);
  cy.get('.leftmenu > .fa').click();
  cy.wait(2000);
  cy.get('.ionicon > [translate=""]').click();
  cy.wait(10000);
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.wait(20000);
  cy.get('#genSortUL > :nth-child(1) > a').click();
  cy.wait(20000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').clear;
  cy.wait(10000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('ABC enviro');
  cy.wait(10000);
  cy.get('.px-3 > .serachpart > .gensearchview > .iconsearch').click();
  cy.wait(5000);
  cy.get('li > .g-name-hd').click();
  cy.wait(5000);
  cy.get('#panel-col').click();
  cy.wait(5000);
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .gen-head > .fs-16').click();
  cy.wait(5000);
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.wait(5000);
  cy.get('#genSortUL > :nth-child(2) > a').click();
  cy.wait(5000);
  cy.get('.col-xs-12 > .genpart-icons > .d-inline-block > a > .fas').click();
  cy.wait(5000);
 // cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('a');
 // cy.wait(5000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('10004');
  cy.wait(5000);
  cy.get('.px-3 > .serachpart > .gensearchview > .iconsearch').click();
  cy.wait(5000);
  cy.get('li > .g-name-hd').click();
  cy.wait(5000);
  cy.get('#panel-col').click();
  cy.wait(5000);
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .gen-head > .fs-16').should('be.visible');
  cy.get('.col-xs-12 > .genpart-icons > .d-inline-block > a > .fas').click();
  cy.wait(5000);
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG > .ft10').click();
  cy.wait(5000);
  cy.get('#genSortUL > :nth-child(3) > a').click();
  cy.wait(5000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').clear;
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('10006');
  cy.get('.px-3 > .serachpart > .gensearchview > .iconsearch').click();
  cy.get('li > .g-name-hd').click();
  cy.get('#panel-col').click();
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .rw-bdr > #part3 > :nth-child(5) > .form-group > .clk-text > .row > .right-align > div').should('be.visible');
  cy.get('.col-xs-12 > .genpart-icons > .d-inline-block > a > .fas').click();
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.get('#genSortUL > :nth-child(4) > a').click();
  cy.get('.px-3 > .serachpart > .gensearchview > .iconsearch').click();
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').clear;
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').clear;
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('bell buckle');
  cy.get('.px-3 > .serachpart > .gensearchview > .iconsearch').click();
  cy.get('li > .g-name-hd').click();
  cy.get('#panel-col').click();
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .rw-bdr > #part3 > :nth-child(2) > .form-group > .clk-text > .row > .right-align > :nth-child(6) > :nth-child(1) > :nth-child(1) > .list-sty-none > :nth-child(1) > div').should('be.visible');
  cy.get('.col-xs-12 > .genpart-icons > .d-inline-block > a > .fas').click();
  //cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
 // cy.get('#genSortUL > :nth-child(5) > a').click();
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.wait(3000);
  cy.get('#genSortUL > :nth-child(4) > a').click();
  cy.wait(3000);
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.wait(3000);
  cy.get('#genSortUL > :nth-child(5) > a').click();
  cy.wait(3000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').clear();
  cy.wait(3000);
  cy.get('.px-3 > .serachpart > .gensearchview > .search-inp').type('bc{enter}');
  cy.wait(3000);
  cy.get('li > .g-name-hd').click();
  cy.wait(3000);
  cy.get('#panel-col').click();
  cy.wait(3000);
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .rw-bdr > #part3 > :nth-child(1) > .form-group > .clk-text > .row > .right-align').should('be.visible');
  cy.wait(3000);
  cy.get('.col-xs-12 > .genpart-icons > .d-inline-block > a > .fas').click();
  cy.wait(3000);
  cy.get('.desk-res-gen > .listfilter > [style="display: inline-block;"] > .gen-SQG').click();
  cy.wait(3000);
  cy.get('#genSortUL > :nth-child(6) > a').click();
  cy.wait(3000);
  cy.get(':nth-child(4) > .row > .col-md-4 > .gen-list > li > .g-name-hd').click();
  cy.wait(3000);
  cy.get('#panel-col').click();
  cy.wait(3000);
  cy.get(':nth-child(1) > .col-md-12 > .mt-5 > :nth-child(1) > .gen-head > .fs-16').should('be.visible');
 
});